### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by brandonchin00** [dkovalenko420/PersonalProject#1]
Hey Danyil!

I love the design of your homepage. It's very unique and super eye-catching. All your links work perfectly. Each page's theme is consistent with your homepage. I really like the hover feature on your navbar. Here are some suggestions for improvement. 

Technical: 
1) I noticed that your homepage has an unnecessary scroll. To remove this do body{ margin: 0; }. 
2) I noticed that your feedback form selections: Great, Good, Awesome can all be selected at once. Instead of using div. Try using <form></form> and assigning your inputs with values. That should prevent the user from selecting all features. 

Suggestions: 
1) I would recommend a short description on the homepage to describe the website's purpose. I wasn't sure what the content was about until I entered other pages. 
2) I recommend resizing your navbar height in the sitemap to match and maintain consistency
3) If you want the white border on your index. Try overflow: hidden; to remove the unnecessary scroll

Overall I love your design of the website! Great work! And I can't wait to see the final product!

**Comment by dkovalenko420** [comment]
Hey Brandon! First of all, I'd like to thank you for such detailed feedback, it truly helped me when redesigning the website for my music project.

I loved your technical suggestions, these are some things other commenters have noticed. However, the scroll and the white bars serve a visual and aesthetic purpose, which is why I am not planning to change them. Regardless, your comment about the form was extremely accurate and I implemented this change already.

Your content feedback was also extremely useful. Unfortunately, I am not planning to add any descriptions for the site. This is because all visitors going to the site will already be familiar with my work. The website link will be available on my Spotify, as well as my Instagram. This is why every visitor will already know this website represents my mucal project "dracodraco." Also, as I mentioned previously, I do not want to remove the scroll (simply because it is intentional). Regardless, thank you very much for the feedback, I found it very useful.
